### PR TITLE
Task 3

### PR DESCRIPTION
**Pull request by yurassic**
## What's done:
Added new service `product-service` with 2 end-points:
https://pcaxnsgpr2.execute-api.eu-west-1.amazonaws.com/products
https://pcaxnsgpr2.execute-api.eu-west-1.amazonaws.com/products/6345de09d5bd3ae51ce01bd2

Also, here is the FE app deployed to CloudFront:
https://d3e7wywm2iga8a.cloudfront.net/

### Additional tasks:
- Async/await is used in lambda functions
- ES6 modules are used for Product Service implementation
-  Lambda handlers (getProductsList, getProductsById) code is written not in 1 single module (file) and separated in codebase.
- Main error scenarios are handled by API ("Product not found" error).

### CODE REVIEW

**Comment by yaspav** [comment]
Good job. Not only required part was done, but also some tasks from the optional part. I gave 9 score: 4 for the required task and 5 for the optional.

**Comment by NickCherny** [comment]
Good. Thanks.!

**Comment by rudnitsi** [comment]
Good job! Sugested score is 9 )

**Comment by rudnitskiivol** [comment]
Good job! Suggested score is 9)

**Pull request merged**
